import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("com.vanniktech.maven.publish")
}

// Single source of truth: VERSION_NAME in sdk-android/gradle.properties.
val sdkVersion: String = providers.gradleProperty("VERSION_NAME").get()

android {
    namespace = "app.stringcast.sdk"
    compileSdk = 36

    defaultConfig {
        minSdk = 21
        consumerProguardFiles("consumer-rules.pro")
        buildConfigField("String", "SDK_VERSION", "\"$sdkVersion\"")
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }
}

kotlin {
    jvmToolchain(17)
    explicitApi()
}

mavenPublishing {
    // Release variant only, with a sources jar and a javadoc jar (generated by AGP/Dokka).
    configure(
        AndroidSingleVariantLibrary(
            variant = "release",
            sourcesJar = true,
            publishJavadocJar = true,
        )
    )

    // Central Portal (central.sonatype.com). Credentials come from the Gradle properties
    // mavenCentralUsername / mavenCentralPassword (ORG_GRADLE_PROJECT_* env vars in CI).
    // Use `publishAndReleaseToMavenCentral` to release automatically after validation.
    publishToMavenCentral()

    // Sign only when a key is configured, so `publishToMavenLocal` works without one.
    // CI provides ORG_GRADLE_PROJECT_signingInMemoryKey (+ KeyId / KeyPassword).
    val hasSigningKey = listOf("signingInMemoryKey", "signing.keyId")
        .any { !providers.gradleProperty(it).orNull.isNullOrBlank() }
    if (hasSigningKey) {
        signAllPublications()
    }

    coordinates("app.stringcast", "stringcast-android", sdkVersion)

    pom {
        name.set("StringCast Android SDK")
        description.set(
            "Over-the-air localization for Android apps: strings, plurals and string arrays " +
                "published in StringCast replace the compiled strings.xml values at runtime."
        )
        inceptionYear.set("2026")
        url.set("https://github.com/stringcast/stringcast-android")
        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("adnanfuentes87")
                name.set("Adnan Fuentes Diaz")
            }
        }
        scm {
            url.set("https://github.com/stringcast/stringcast-android")
            connection.set("scm:git:git://github.com/stringcast/stringcast-android.git")
            developerConnection.set("scm:git:ssh://git@github.com/stringcast/stringcast-android.git")
        }
    }
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")
    implementation("androidx.core:core:1.13.1")

    testImplementation("junit:junit:4.13.2")
    // android.jar ships org.json as stubs; use the real implementation on the JVM.
    testImplementation("org.json:json:20240303")
}
