package app.stringcast.sdk.internal

/**
 * Decides which resource names are "the app's own strings" for draft mode (automatic upload,
 * [app.stringcast.sdk.StringCast.uploadLocalStrings] and missing-key reports).
 *
 * Why a built-in denylist: with AGP 8's default *non-transitive* R classes an app module's `R`
 * only contains that module's resources, but apps built with `android.nonTransitiveRClass=false`
 * (legacy) get every library's resources merged into their `R` — AppCompat (`abc_*`), Material
 * (`mtrl_*`, `m3_*`), Compose (`m3c_*`, `tab`, `selected`, …), ExoPlayer/Media3 (`exo_*`), Play
 * services / Firebase / Facebook (`common_google_play_services_*`, `google_app_id`, …). Those are
 * not the app's text and must never be uploaded to the project. The list below names those
 * libraries' strings; apps add their own exclusions through `StringCastConfig.excludedKeys` and
 * `StringCastConfig.excludedKeyPrefixes`.
 *
 * [LIBRARY_PREFIXES] are library namespaces (`abc_` matches `abc_action_bar_home_description`).
 * [LIBRARY_EXACT] are complete library resource names and generated values; they match only that
 * exact name, so an app's own `tab_home` or `selected_count` is never dropped because of `tab` /
 * `selected`.
 */
internal class KeyFilter(
    excludedKeys: Set<String> = emptySet(),
    excludedKeyPrefixes: Set<String> = emptySet(),
) {
    private val exact: Set<String> = excludedKeys.mapNotNullTo(HashSet()) { it.trim().ifEmpty { null } }
    private val prefixes: List<String> = excludedKeyPrefixes.mapNotNull { it.trim().ifEmpty { null } }

    /** True if [name] must never be uploaded or reported. */
    fun isExcluded(name: String): Boolean {
        if (name.isEmpty()) return true
        if (name in LIBRARY_EXACT || name in exact) return true
        for (p in LIBRARY_PREFIXES) if (name.startsWith(p)) return true
        for (p in prefixes) if (name.startsWith(p)) return true
        return false
    }

    companion object {
        /** Library / generated resource-name rules (see the class comment for the matching rules). */
        val LIBRARY_PREFIXES: List<String> = listOf(
            // AppCompat, Material Components, Material 3 (views + Compose), Media3/ExoPlayer
            "abc_", "exo_", "mtrl_", "material_", "m3_", "m3c_",
            "bottomsheet_", "character_counter_", "searchview_", "side_sheet_", "call_notification_",
            "path_password_", "item_view_role_", "fab_transformation_",
            // Play services, Firebase Cloud Messaging, AndroidX
            "common_google_play_services_", "common_signin_button_", "fcm_", "androidx_",
        )

        /** Complete library resource names, plus values generated by google-services / Crashlytics / Facebook. */
        val LIBRARY_EXACT: Set<String> = setOf(
            // Material views
            "password_toggle_content_description", "hide_bottom_view_on_scroll_behavior",
            "appbar_scrolling_view_behavior", "bottom_sheet_behavior", "clear_text_end_icon_content_description",
            "error_icon_content_description", "exposed_dropdown_menu_content_description", "icon_content_description",
            "search_menu_title", "status_bar_notification_info_overflow", "common_open_on_phone",
            // Compose UI / Material accessibility strings
            "default_popup_window_title", "dropdown_menu", "close_drawer", "close_sheet", "navigation_menu",
            "range_start", "range_end", "selected", "not_selected", "switch_role", "tab",
            "state_empty", "state_off", "state_on", "indeterminate", "in_progress", "template_percent",
            "tooltip_description", "tooltip_label", "collapsed", "expanded", "toggle_button_role",
            // google-services / Crashlytics / Facebook
            "google_app_id", "gcm_defaultSenderId", "default_web_client_id", "google_api_key",
            "google_crash_reporting_api_key", "google_storage_bucket", "project_id", "firebase_database_url",
            "com.google.firebase.crashlytics.mapping_file_id", "com.crashlytics.android.build_id",
            "facebook_app_id", "facebook_client_token", "fb_login_protocol_scheme",
        )
    }
}
